import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { lazy } from "react";
import StoreProvider from "@/src/lib/redux/StoreProvider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });
const Dimension = dynamic(() => import("@/src/hook/useDevice"), {
  ssr: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="main" className={inter.className}>
        <StoreProvider>
          <Dimension />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
