import StoreProvider from "@/src/lib/redux/StoreProvider";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Dimension = dynamic(() => import("@/src/hook/useDevice"), {
  ssr: false,
});

const SnackProvider = dynamic(
  () => import("@/src/lib/notistack/SnackbarProvider"),
  {
    ssr: false,
  }
);

const MuiThemeProvider = dynamic(() => import("@/src/lib/mui/ThemeProvider"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className} style={{ position: "relative" }}>
        <MuiThemeProvider>
          <StoreProvider>
            <SnackProvider>
              <Dimension />

              {children}
            </SnackProvider>
          </StoreProvider>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
