import { Box, Typography } from "@mui/material";
import { GREETING } from "./weather/const";
import { date } from "@/src/lib/dayjs/date";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { useAppSelector } from "@/src/lib/redux/store";

export const metadata: Metadata = {
  title: "Ted's Forecast - Weather",
  description: "Weather forecast dashboard generated by NextJs",
};
const NavBar = dynamic(() => import("@/app/(dashboard)/components/NavBar"), {
  ssr: false,
});
export default function WeatherLayout(props: { children: React.ReactNode }) {
  const mainTheme = GREETING.find(
    (el) => Number(date().format("HH")) >= el.hour
  );

  return (
    <Box
      sx={{
        position: "relative",
        background: mainTheme?.color,
        color: "#0A0A0B",
        fontFamily: "'Roboto', sans-serif;",
        height: "100vh",
        overflow: "hidden",
      }}
    >
      <NavBar />
      <Box height={`calc(100% - 74px)`}>{props.children}</Box>
    </Box>
  );
}
